timeout: 1800s # Cache misses are slow to rebuild
steps:
  - id: "Load cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      source scripts/ci.sh
      load-cache
      apt-get update
      apt-get -y install postgresql libpq-dev

  - id: "Build deps"
    name: 'haskell:8.4.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      stack config set system-ghc --global true
      stack config set install-ghc --global false
      stack install stylish-haskell hlint

  - id: "Format"
    name: 'haskell:8.4.3'
    waitFor: ["Build deps"]
    env: ['STACK_ROOT=/workspace/.stack']
    args: ['./scripts/check-fmt.sh']

  - id: "Lint"
    name: 'haskell:8.4.3'
    waitFor: ["Build deps"]
    env: ['STACK_ROOT=/workspace/.stack']
    args: ['stack', 'exec', '--', 'hlint', '.']

  - id: "Build"
    name: 'haskell:8.4.3'
    waitFor: ["Load cache"]
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      stack build --fast --no-terminal --pedantic

  - id: "Test"
    name: 'haskell:8.4.3'
    waitFor: ["Build"]
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      stack test --fast --no-terminal --pedantic

  - id: "Build reference document"
    name: 'haskell:8.4.3'
    waitFor: ["Build"]
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      stack exec radicle-ref-doc

  - id: "Build ghcjs"
    name: "haskell:8.4.3"
    waitFor: ["Load cache"]
    env: ["STACK_ROOT=/workspace/.stack"]
    entrypoint: bash
    args:
      - '-c'
      - |
        stack install alex happy
        bash scripts/ci-ghcjs.sh

  - id: "Save cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      source scripts/ci.sh
      save-cache

