name: radicle
version: '0.0.0'
author: Monadic <team@monadic.xyz>
maintainer: Monadic <team@monadic.xyz>
license: BSD3
git: oscoin/radicle
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4 && <5
- containers
- haskeline
- lens
- megaparsec
- mmorph
- mtl
- prettyprinter
- text

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    ghc-options: -Wall -threaded
    dependencies:
    - radicle
    - QuickCheck
    - quickcheck-instances
    - string-qq
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
  doctest:
    main: Main.hs
    source-dirs:
    - test/docs
    ghc-options: -Wall -threaded
    other-modules:
    - Paths_radicle
    dependencies:
    - radicle
    - doctest
    - Glob
    - hpack

executables:
  repl:
    main: Repl.hs
    source-dirs:
    - exe
    dependencies:
    - radicle
    ghc-options: -Wall -threaded

default-extensions:
- AutoDeriveTypeable
- ConstraintKinds
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- RecordWildCards
- TupleSections
- TypeFamilies
- TypeOperators
